### ISSUE TITLE
how to show different login pages?

### ISSUE THREAD

**Issue by donatiss** [ultraware/roles#10]
for example, i need user levels:
1 -> user -> user login (default laravel)
2 -> seller -> seller login (new one for that)
3 -> owner -> web owner login page (another new one for this one too)

and i need all successful redirects to access that login, logout and ect. 
lets say:
- in my web is comming **guest**. he can just see information.
- when comming **user**, he press _login_ button and see Hello USER, please login (views/auth/login.user.blade.php) [url = domain.com/login].
- when comming **seller** and press button _seller login_, he need to see Hello SELLER, please login (views/auth/login.seller.blade.php) [url = domain.com/seller].
- when owner is comming - he just enter url (ex. domain.com/adminLTE) and see Welcome back, ADMIN, enter your details (views/auth/login.admin.blade.php) [url = domain.com/adminLTE].

thanks for help, 'cause i'm new in Laravel and don't understand.

edit:
i have created roles for that with slug and level, but just need different logins. 
btw -> 
- **owner** can see all stuff of _seller_ and _user_
- **seller** can see _user_ stuff
- **user** can see just _guest_ stuff + a little bit new features from guest (comment and ect)
[here i understand - i need to use levels (i hope so)] 👯‍♂️

**Comment by Ricky-rick** [comment]
You can use levels to accomplomise that. See the readme:
https://github.com/ultraware/roles#permissions-inheriting

**Comment by jacurtis** [comment]
Yes this is a common confusion. Multi-Auth is designed for entirely different and unrelated user types. This is in contrast to user roles, which are the same types of users, but with different levels of permissions or authority.
