### ISSUE TITLE
Show permissions

### ISSUE THREAD

**Issue by tripex** [ultraware/roles#16]
Hi, it is possible to add some permissions to a role, and then assign the role to the user.
However, is it possible to disable some of the permissions on the role only for one particular user?

It sounds like a really awesome package.

**Comment by Skintillion** [comment]
Why not make a new role?

**Comment by tripex** [comment]
Hi Again. 
it's because I will use the roles as a position identifier, let me give you an example. 

role = developer
permissions = can do release, can push to prod, can do rollback, and so on. 

So i hire a new guy, his position is developer, but because he is new he need to learn how to do a release before he should have this permission. 

I would like this approach instead of having a role called "new developer can do release"

And i just think it's easier for me that the permissions is shown and then i can just tick them on when ready.

**Comment by Skintillion** [comment]
You will over complicate by trying to bypass the easy route of just making another developer role such as Apprentice Developer and giving it the specified permissions.

**Comment by tripex** [comment]
Well I think extra roles for every permission is overcomplicated, but thanks for your answer. 
Right now I can't see the logical in having multiple roles for the same thing.
I wil try figure something out that suits my way better :) Maybe create my own simple system.
