### ISSUE TITLE
Laravel 5.5 Blade directives

### ISSUE THREAD

**Issue by baine101** [ultraware/roles#18]
I seem to have the Blade directives @role() etc  rendered as text in laravel 5.5 after switching from romanbicans last version. 

I have checked the source files for both RolesServiceProvider's registerBladeExtensions function and they are near identical apart from the directory location.

I have migrated from a laravel 5.2 application to 5.5 and upgraded from romanbican's 2.1 version to ultraware's 5.5 version

**Comment by Ricky-rick** [comment]
Hi,

Is the service provider correctly loaded?
Do the other other directives stil work?

**Comment by danlupascu** [comment]
I had the same issue. Also migrating from 5.2 to 5.5. I don't know what exactly happened but It is working now. I uninstalled and installed the package again and it seems that it is working now. Also, after installing it again just run `php artisan view:clear`. I hope this helps 

Edit: after clearing the cache they stopped working again. So I searched and found a solution. It should work now.

**Comment by SlFomin** [comment]
Excess procedural solution, in my opinion, but all that was worth doing is to use the class created for this, the code becomes cleaner and more beautiful
Example([src/RolesServiceProvider.php](https://github.com/ultraware/roles/blob/5.5/src/RolesServiceProvider.php)):
```PHP
use Illuminate\Support\Facades\Blade;
...
    protected function registerBladeExtensions()
    {
        Blade::directive('role', function ($expression) {
            ...
        });

        Blade::directive('endrole', function () {
            ...
        });

        //and all for this template

    }
```
Then still it is necessary to delete a procedural line, after all now the class:
```PHP
$blade = $this->app['view']->getEngineResolver()->resolve('blade')->getCompiler();
```
Tested on Laravel 5.5.20

**Comment by Ricky-rick** [comment]
The blade directives are case sensitive. All blade directives in the roles package are lowercase so you need to use ```@role(...)```  and ```@endrole```

I can't reproduce this issue with the directive in lower case
