### ISSUE TITLE
Middleware VerifyPermission always returns true

### ISSUE THREAD

**Issue by giwrgos88** [ultraware/roles#3]
Hello, I saw that the VerifyPermission is not working properly. Basically it's always returning true event if the user doesn't have the permission.
For example I have two types of roles, the one is admin who has permission on roles route and the client who doesn't have access to role route. Route:

```php
Route::get('/users/roles', ['as' => 'admin.users.roles', 'middleware' => 'permission:edit.roles', 'uses' => 'UsersController@roles']);
```
If I access the route with the admin is working fine. If I access the route with client it supposed to throw an error but it doesn't, loads the page.

So I did ```dd($this->auth->user()->userPermissions);``` to see the permissions of the client and the permission:edit.roles wasn't in his list. 

So I fix it like this

```php

	/**
	 * Handle an incoming request.
	 *
	 * @param Request $request
	 * @param \Closure $next
	 * @param int|string $permission
	 * @return mixed
	 * @throws \Ultraware\Roles\Exceptions\PermissionDeniedException
	 */
	public function handle($request, Closure $next, $permission) {
		$permissionsList = $this->auth->user()->userPermissions->pluck('slug')->toArray();
		if ($this->auth->check() && in_array($permission, $permissionsList)) {
			return $next($request);
		}

		throw new PermissionDeniedException($permission);
	}

```

**Comment by Ricky-rick** [comment]
Permissions can be attached to user directly (`$this->auth->user()->userPermissions`) and through a role (`$this->auth->user()->rolePermissions`)
Maybe the permission is attached through a role? 
What is returned by:
`dd($this->auth->user()->getPermissions);`

**Comment by giwrgos88** [comment]
the ```$this->auth->user()->getPermissions``` returns the permissions which are attached to the user where ```permission:edit.roles``` is attached to admin but not on client

**Comment by Ricky-rick** [comment]
I can't reproduce the issue.
If you do the following for the client does it contain the 'edit.roles' permission
`dd($this->auth->user()->getPermissions());`

**Comment by giwrgos88** [comment]
If I do ```dd($this->auth->user()->getPermissions());``` I have inside the edit role, see image 1.
The number 3 is the ID of the user

<img width="981" alt="image1" src="https://cloud.githubusercontent.com/assets/3164113/22300683/e7dcf5f8-e330-11e6-8c7e-8ee884c0d25c.png">

The other two images are the values inside the database, users with permissions and roles and permissions

<img width="494" alt="screen shot 2017-01-25 at 7 03 15 pm" src="https://cloud.githubusercontent.com/assets/3164113/22300706/ff2e9842-e330-11e6-87f4-51539f227507.png">
<img width="471" alt="screen shot 2017-01-25 at 7 03 20 pm" src="https://cloud.githubusercontent.com/assets/3164113/22300707/ff2f690c-e330-11e6-8150-054ed12c6070.png">

**Comment by Ricky-rick** [comment]
Is there a connection between role (1, 2) and the user in the user_role table?

**Comment by giwrgos88** [comment]
Yes there is a connection between them

<img width="476" alt="screen shot 2017-02-03 at 9 27 14 am" src="https://cloud.githubusercontent.com/assets/3164113/22583015/0598a7f4-e9f3-11e6-8815-896e4d214575.png">

**Comment by reke592** [comment]
I have the same issue.
here's my seeder pseudo
// create permissions
// create roles
// sync permissions to roles
// create user
// attach role(s) to user

in my case, I created 2 roles (hr.officer, finance.officer)
I attach only the finance.officer role to the user but when I run the $user->getPermissions();
it returns also the hr.officer permissions.

**Comment by reke592** [comment]
I think, the ->orWhere('roles.level', '<', $this->level()) is the cause, this will return all the permissions of all roles with lower level

    /**
     * Get all permissions from roles.
     *
     * @return Builder
     */
    public function rolePermissions()
    {
        $permissionModel = app(config('roles.models.permission'));

        if (!$permissionModel instanceof Model) {
            throw new InvalidArgumentException('[roles.models.permission] must be an instance of \Illuminate\Database\Eloquent\Model');
        }

        return $permissionModel
            ::select(['permissions.*', 'permission_role.created_at as pivot_created_at', 'permission_role.updated_at as pivot_updated_at'])
            ->join('permission_role', 'permission_role.permission_id', '=', 'permissions.id')
            ->join('roles', 'roles.id', '=', 'permission_role.role_id')
            ->whereIn('roles.id', $this->getRoles()->pluck('id')->toArray())
            ->orWhere('roles.level', '<', $this->level())
            ->groupBy(['permissions.id', 'permissions.name', 'permissions.slug', 'permissions.description', 'permissions.model', 'permissions.created_at', 'permissions.updated_at', 'pivot_created_at', 'pivot_updated_at']);
    }

**Comment by reke592** [comment]
... OK, now I get the logic of the role level. haha

**Comment by Ricky-rick** [comment]
Great!
If you don't want to use the level feature just add all roles with level 1.
@giwrgos88 What are the levels at you're roles table??

**Comment by giwrgos88** [comment]
@Ricky-rick sorry for the long response

<img width="449" alt="screen shot 2017-02-16 at 6 55 27 pm" src="https://cloud.githubusercontent.com/assets/3164113/23031404/878cc282-f479-11e6-8c65-290f7b46ebac.png">

**Comment by giwrgos88** [comment]
@Ricky-rick why closed?

**Comment by Ricky-rick** [comment]
I thought it was clear that the issue is caused by the level of your roles. 
From the readme :

Permissions Inheriting

Role with higher level is inheriting permission from roles with lower level.

There is an example of this magic:

You have three roles: user, moderator and admin. User has a permission to read articles, moderator can manage comments and admin can create articles. User has a level 1, moderator level 2 and admin level 3. It means, moderator and administrator has also permission to read articles, but administrator can manage comments as well.

If you don't want permissions inheriting feature in you application, simply ignore level parameter when you're creating roles.

**Comment by giwrgos88** [comment]
@Ricky-rick ok, thanks a lot
