### ISSUE TITLE
Error on validate permission

### ISSUE THREAD

**Issue by JaimeVirrueta** [ultraware/roles#5]
I have a problem, and it is that in my case I do not use the slug, but of uuid and it is manual, I do not use a package, by which when validating it tells me that I do not have permission which is incorrect

`$row->name = 'access-admin';`
`$row->uuid = '79091018328db1b20b89ce6c46ce16ac';`

And in the validation tarot look for a defined slug

`line 278 of HasRoleAndPermission`

`public function checkPermission($permission)`
`   {`
`        return $this->getPermissions()->contains(function ($value) use ($permission) {`
`            return $permission == $value->id || Str::is($permission, $value->slug);`
`        });`
`    }`
i change the `$value->slug` for `$value->uuid`

The problem is that when updating the package will change the "uuid" by the "slug",as it would in this particular case?

**Comment by Ricky-rick** [comment]
In checkRole and checkPermission the `$value` in `$value->slug` is a role/permission model. You can extend the default role and permission model of this package and add Accessor for the slug.
https://laravel.com/docs/5.4/eloquent-mutators#defining-an-accessor
