### ISSUE TITLE
Allow more settings in Route middleware

### ISSUE THREAD

**Issue by Xety** [ultraware/roles#9]
For exemple, actually we can do :
```php
'middleware' => [
    'permission:access.site'
]
```
But what about something like that :
```php
'middleware' => [
    'permission:access.site,level:4,role:admin'
]
```
Convert this to :
```
IF the user has the permission access.site OR has the level >= 4 OR has the role admin
    The user is authorized
ELSE
    The user is not authorized
```
Of course that is just an exemple. But i think we can use that to do complexe permissions without being hard to understand and code.
We can also use the variadic syntax (PHP >= 5.6) to get the parameters `...$permission` and it will return and array :
```php
[
    "access.site"
    "level:4"
    "role:admin"
]
```

I have thinked about that when i needed to allow guest to access to a page but not certain logged in users releated to a group. (So i have made a custom middleware for that)

**Comment by Ricky-rick** [comment]
I like the idea of more flexibility in the middleware. 
I think the best way to implement this is through Laravel gates and/or Policies.
In the policy or gate you receive the user and you can simply check the permission / role and level of the user.
```php
return ($user->hasPermission('access.site') || $user->hasRole('admin') || $user->level() >= 4);
```
You can use the gate/policy as middleware and you can also use the gate/policy on the user model, the controller helper and even in blade. This gives you much more flexibility.

Let me know if this works for you and if you have any ideas for a better integrations with the Laravel policies and gates.
